_BASE_: "./Base-C2_L_R5021k_640b64_4x.yaml"
SOLVER:
  MAX_ITER: 90000 
  CHECKPOINT_PERIOD: 9000
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  MODEL_EMA: 0.999 # ae
DATASETS:
  TRAIN: ("lvis_v1_train",)
  TEST: ("lvis_v1_val",)
MODEL:
  WEIGHTS: "models/baseline_R50.pth"
INPUT:
  INST_POOL: false
  INST_POOL_FEED: true
  INST_POOL_PATH: "/annotations"  # "YOUR_DATASET_ANNOTATION_PATH"
  INST_POOL_ROOT: "/images" # "YOUR_DATASET_IMAGES_PATH"
  INST_POOL_FORMAT: "RGBA"
  USE_COPY_METHOD: "syn_copy"
  USE_INSTABOOST: false
  MASK_FORMAT: bitmask
  CP_METHOD: ['basic']
  RANDOM_ROTATE: false
  INST_POOL_SAMPLE_TYPE: "uniform" 
  TRAIN_SIZE: 640
  ROUND_RESET: true
  INIT_ROUND: false
  NUM_ROUNDS: 10
  LOG_SCP_PARAM: true
TEST:
  EVAL_PERIOD: 9000
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
  NUM_WORKERS: 8
  PREFETCH_FACTOR: 8
