_BASE_: "./Base-C2_L_R5021k_640b64_4x_embed.yaml"
SOLVER:
  MAX_ITER: 90000 
  CHECKPOINT_PERIOD: 9000
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  MODEL_EMA: 0.999 # ae
DATASETS:
  TRAIN: ("lvis_v1_train",)
  TEST: ("lvis_v1_val",)
MODEL:
  WEIGHTS: "models/baseline_SwinL.pth"
INPUT:
  TRAIN_SIZE: 640
TEST:
  EVAL_PERIOD: 9000
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
  NUM_WORKERS: 8
  PREFETCH_FACTOR: 8
